sources:
  - name: Kali
    handler:
      graphql:
        # Default value is kali-mainnet
        # This is needed for the initial introspection on buildtime
        endpoint: https://api.thegraph.com/subgraphs/name/nerderlyne/{context.chainName:kali-mainnet}
    transforms:
      # Enable Automatic Block Tracking
      - blockTracking:
          validateSchema: true
      - autoPagination:
          validateSchema: true

additionalTypeDefs: |
  extend type DAO {
    chainName: String!
  }

additionalResolvers:
  - ./graph/resolvers.ts

documents:
  - "./graph/**/*.graphql"

codegen:
  contextType: "MeshContext & { chainName: string }"
